.github/workflows/app.yml
.github/workflows/issue-triage.yml
.github/workflows/main.yml
scripts/integration-server-conduit.sh
scripts/integration-server-dendrite.sh
scripts/integration-server-synapse.sh
scripts/test.sh
scripts/test_driver.sh
test_driver/synapse/data/homeserver.yaml

The pulish step is still missing, maybe someone else can implement that one :)

feat: Use github actions

---

lib/src/utils/uia_request.dart

(Also prevents a potential out of bounds exception)

refactor: simplify UIA stage selection logic

---

lib/src/client.dart
test_driver/matrixsdk_test.dart

If you create DM room, but the other party doesn't join it, they might be unable to create a new DM using startDirectChat. Since creating a new DM is pretty much the same as joining the invite, we try to join the pending DM invite first and fall back to creating a new room if that fails.

fix: startDirectChat might return an unjoined room

---

lib/src/client.dart

Apply state event before decryption on leaved room

---

.github/workflows/app.yml
lib/encryption/utils/bootstrap.dart

Otherwise uploading the keys won't work, since the key backup is "disabled".

fix: wait for online key backup key to be cached on reset

---

lib/src/room.dart

Otherwise the user can't handle that exception themselves, since we don't rethrow.

fix: Wait for rate limit to pass while sending messages

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/epic.yml
.github/ISSUE_TEMPLATE/feature.yml
.github/ISSUE_TEMPLATE/improvement.yml

Related to https://github.com/famedly/product-management/issues/1355

chore: Added adjusted issue templates from product-management

---

lib/src/voip/call.dart

Fixes https://github.com/famedly/product-management/issues/1399. Need someone to also make sure this change doesn't affect any other flow. For more details, read up the conversation in the issue.

fix: call hangup on timeout race condition

---

lib/src/voip/call.dart

Closes #https://github.com/famedly/product-management/issues/1475

Hangup on call crash

---

lib/src/client.dart
lib/src/database/database_api.dart
lib/src/database/hive_collections_database.dart
lib/src/database/hive_database.dart
lib/src/presence.dart
lib/src/user.dart
test/database_api_test.dart

Closes https://github.com/famedly/matrix-dart-sdk/issues/291

feat: Store presences in  database

---

lib/src/utils/commands_extension.dart

Makes debugging and hacking
easier

feat: Add sendRaw command

---

lib/encryption/encryption.dart
lib/encryption/olm_manager.dart
lib/msc_extensions/msc_3814_dehydrated_devices/api.dart
lib/msc_extensions/msc_3814_dehydrated_devices/msc_3814_dehydrated_devices.dart
test/fake_matrix_api.dart
test/msc_extensions/msc_3814_dehydrated_devices_test.dart

BREAKING CHANGE: This replaces the old dehydrated devices implementation, since there is no way to query what is supported easily and supporting both would be complicated.
fixes https://github.com/famedly/matrix-dart-sdk/issues/1579

feat: Update dehydrated devices implementation to current MSC

---

lib/src/voip/voip.dart

Closes https://github.com/famedly/product-management/issues/1512

handle call when multiple devices are involved for one account

---

lib/src/voip/voip.dart

Closes https://github.com/famedly/product-management/issues/1617

fix: set cid before initWithInvite to properly end call on getUserMedia exception

---

lib/encryption/key_manager.dart
lib/src/client.dart

Closes https://github.com/famedly/matrix-dart-sdk/issues/361

refactor: Make possible to wait for first sync and await first sync before create megolm session

---

lib/src/client.dart

Tested in FluffyChat on iOS and worked good for me. Initial sync was much faster :-)
This fixes the response
timeout for the initial
sync and sets it to 2
minutes instead of 10
seconds. This should increase
the speed for the initial
sync especially for large
accounts. This change
also adds some
documentation in the
code about what
timeout does what.

fix: Increase timeout for initial sync from 10 seconds to 2 minutes

---

lib/src/client.dart
lib/src/voip/call.dart
lib/src/voip/group_call.dart
lib/src/voip/voip.dart
test/calls_test.dart
test/room_test.dart
test/webrtc_stub.dart

Fixes: https://github.com/famedly/product-management/issues/1469

fix: ignore calls with age older than lifetime

---

lib/src/database/matrix_sdk_database.dart

https://github.com/krille-chan/fluffychat/issues/735#issuecomment-1870371975

fix: Add missing copy map in matrix sdk database

---

lib/encryption/olm_manager.dart
lib/src/client.dart

Fixes https://github.com/famedly/product-management/issues/55

refactor: Use maxnumberofotk from olm instead hardcode 100

---

lib/src/client.dart
lib/src/room.dart

Completes part of https://github.com/famedly/product-management/issues/1110

feat: specify history_visibility when creating group chat

---

lib/src/voip/call.dart
lib/src/voip/group_call.dart

Fixes: https://github.com/famedly/product-management/issues/1543
some of the flags are deprecated, needs testing

chore: add noice/echo cancelling flags to getUserMedia

---

lib/src/client.dart

This also makes sure that
the access token is
refreshed when calling
client.getEventByPushNotification()
which is porbably the most
common case for a client
with a stopped sync loop
doing network requests.

feat: Offers client.ensureNotSoftLoggedOut() to fix using client with stopped sync loop

---

lib/encryption/key_manager.dart
lib/src/client.dart
lib/src/database/database_api.dart
lib/src/database/hive_collections_database.dart
lib/src/database/hive_database.dart
lib/src/database/matrix_sdk_database.dart
lib/src/room.dart
test/client_test.dart
test/database_api_test.dart
test/room_test.dart
test_driver/matrixsdk_test.dart

closes https://github.com/famedly/matrix-dart-sdk/issues/360

refactor: Store lastEvent in room object instead of room state

---

lib/encryption/key_manager.dart

Closes https://github.com/famedly/matrix-dart-sdk/issues/1739

fix: Typo in upload key json object creates invalid objects

---

lib/src/client.dart

closes https://github.com/famedly/product-management/issues/1661

chore: Sort archive by last activity

---

README.md
doc/get-started.md
doc/web.md
lib/src/database/matrix_sdk_database.dart

docs: Add documentation

---

lib/src/timeline.dart

When using the searchEvent()
method it was impossible to
paginate to the next
chunk when one chunk had
0 returned events. This
fixes it by returning the
prevBatch and makes it
possible to insert the prevBatch
again. sinceEventId is still
working but now deprecated.

refactor: Use prevBatch from server for pagination in event search

---

lib/src/room.dart

The direct chat account data
content is a map from matrixId
to roomId(s). If we want to find
the roomId for a given userId,
then this is not a problem. But
the other way around, if we
want to check if a given roomId
is a direct chat or not, needs to
process all entries which can be
hundreds. Doing this very
often in an app costs a lot of
performance. This adds a simple
cache in the room object and
validates the cache every time
to make this more efficient.

refactor: Cache direct chat matrix ID

---

lib/msc_extensions/msc_unpublished_custom_refresh_token_lifetime/msc_unpublished_custom_refresh_token_lifetime.dart
lib/src/client.dart

Custom client implementation of
https://github.com/famedly/synapse/pull/10

feat: Implement unpublished MSC custom refresh token lifetime

---

lib/src/room.dart

Closes https://github.com/famedly/product-management/issues/2020

fix: update event status to error on EventTooLarge

---

lib/src/client.dart
lib/src/event.dart
test/fake_client.dart
test/room_archived_test.dart
test/timeline_context_test.dart
test/timeline_test.dart

refactor: Make network request timeout

---

CHANGELOG.md
lib/src/voip/backend/livekit_backend.dart
pubspec.yaml

feat: hide _makeNewSenderKey and expose a new preShareKey function

---

lib/src/database/hive_collections_database.dart
lib/src/database/hive_database.dart

Same fix from https://github.com/famedly/matrix-dart-sdk/pull/1835 has to applied to other two places.

fix: Do not return invalid state events from database

---

.github/workflows/app.yml

successful run: https://github.com/famedly/matrix-dart-sdk/actions/runs/9612117610

chore: use not cancelled in actions instead of always

---

.github/workflows/app.yml
.github/workflows/versions.env
scripts/integration-prepare-alpine.sh
scripts/integration-prepare-homeserver.sh
scripts/integration-server-conduit.sh
scripts/integration-server-dendrite.sh
scripts/integration-server-synapse.sh
scripts/test_driver.sh
test_driver/matrixsdk_test.dart

https://github.com/dart-lang/sdk/issues/54877
also fixes: https://github.com/famedly/product-management/issues/1951

fix: bump flutter and dart versions for right analyzer json format

---

lib/src/client.dart
lib/src/room.dart
test/room_test.dart

Fixes: https://github.com/famedly/product-management/issues/2155

fix: lastEvent after edit and redact

---

lib/encryption/key_manager.dart
test/encryption/key_manager_test.dart

fixes https://github.com/famedly/product-management/issues/2106

fix: Correctly store lastEvent in database after decryption

---

lib/src/client.dart
lib/src/room.dart

fixes https://github.com/famedly/product-management/issues/2126

feat: Automatically cancel typing indicators after 30 seconds

---

lib/src/event.dart
test/timeline_test.dart

superseeds: https://github.com/famedly/matrix-dart-sdk/pull/1631/files
fixes: https://github.com/famedly/product-management/issues/1020

fix: add main thread receipts to event.receipts getter

---

lib/src/client.dart
lib/src/database/database_api.dart
lib/src/database/indexeddb_box.dart
lib/src/database/matrix_sdk_database.dart
lib/src/database/sqflite_box.dart
pubspec.yaml
test/box_test.dart
test/client_test.dart
test/fake_client.dart
test/fake_database.dart

to be paired with https://github.com/famedly/app/pull/5890
Tested ^ on android, ios and web, also tested migration from main to that branch on android seems to work.

fix: also delete db on logout

---

README.md
lib/src/event.dart
lib/src/event_status.dart
lib/src/utils/matrix_default_localizations.dart
lib/src/utils/matrix_localizations.dart
test/event_test.dart
test/fake_client.dart
test/room_test.dart

Fixes: https://github.com/famedly/product-management/issues/1684

fix: update last event properly on cancel send

---

lib/src/client.dart

Closes https://github.com/famedly/matrix-dart-sdk/pull/1903

refactor: Also use authenticated media if unstable features claim support

---

lib/src/voip/voip.dart

Closes https://github.com/famedly/product-management/issues/2142

chore: Lower loglevel for call event with unexpected sender

---

lib/src/event.dart

- update the emote base regex
- update documentation about emote computation
- add source for the emote regex
- explain use of regex replace instead of `calcUnlocalizedBody`
- split the RegEx sequences into smaller parts in order to increase maintainability and readability

chore: update Emote-only expressions

---

lib/matrix_api_lite/generated/model.dart

OpenAPI change: https://github.com/famedly/dart_openapi_codegen/pull/52

feat: Add additional properties for LoginFlow type

---

lib/matrix_api_lite/generated/api.dart

Closes https://github.com/famedly/product-management/issues/2537
Result of https://github.com/famedly/dart_openapi_codegen/pull/53

feat: Optional authentication for profile requests

---

lib/src/database/database_api.dart
lib/src/database/database_file_storage_io.dart
lib/src/database/database_file_storage_stub.dart
lib/src/database/hive_collections_database.dart
lib/src/database/hive_database.dart
test/database_api_test.dart

feat: Add deleteFile() endpoint to database

---

lib/src/room.dart

This has been deprecated since
https://spec.matrix.org/v1.7/client-server-api/#actions
An empty list of actions should now
be equal to a list with the entry
"dont_notify". Clients should
ignore this action and use
empty lists instead. A good
explaination can be found
https://github.com/matrix-org/matrix-spec-proposals/blob/main/proposals/3987-push-actions-clean-up.md
closes https://github.com/famedly/product-management/issues/2575
Should be backwards compatible. This also adds type safety in the push rule getter by using the already existing parser.

refactor: Do not set the deprecated dont_notify action in push rules

---

lib/src/room.dart
lib/src/timeline.dart

This pull request introduces the StateFilter parameter to several methods within the codebase to allow for more granular control over the types of events being requested. This change enhances the flexibility of event requests, allowing for more specific event type filtering.
**Before:**
When using the requestHistory method, requesting a specific number of events (e.g., 10) could result in fewer events being returned, or none at all, even though there are more relevant chat events available. This happens because the default behavior checks all event types, not just the desired ones. In a chat application, when scrolling backwards or forwards, users expect to receive a consistent number of messages (e.g., 10), and only fewer when reaching the end of the available messages.
**After:**
By …

feat: support filtering events when requesting events history or future

---

lib/src/client.dart
test/client_test.dart

This makes it possible to track
the process of initialization in the
client by just enhancing what
the onMigration callback already
does.

feat: (BREAKING) Replace onMigration with advanced callback onInitStateChanged

---

lib/src/database/matrix_sdk_database.dart

closes https://github.com/famedly/matrix-dart-sdk/issues/1856

refactor: Store room states as triple keys

---

lib/src/client.dart
test/client_test.dart

Closes https://github.com/famedly/product-management/issues/2399

fix: clear legacy db on logout

---

lib/src/room.dart
lib/src/utils/pushrule_evaluator.dart
test/pushevaluator_test.dart

Closes https://github.com/famedly/matrix-dart-sdk/issues/1964

feat: support push rule conditions event_property_is & event_property_contains

---

.github/workflows/app.yml
.github/workflows/publish.yml

Part of https://github.com/famedly/product-management/issues/2320

build: Add timeouts to all ci jobs

---

lib/src/utils/push_notification.dart

closes https://github.com/famedly/matrix-dart-sdk/issues/2014

fix: PushNotification fromJson - toJson fails

---

lib/src/event.dart
lib/src/utils/matrix_file.dart

Part of https://github.com/famedly/app/issues/6379

fix: incorrect mimeType for files when downloading

---

lib/src/room.dart

Closes https://github.com/famedly/matrix-dart-sdk/issues/1831

fix: room prev_batch set incorrectly

---

lib/src/client.dart
lib/src/room.dart

Closes https://github.com/famedly/matrix-dart-sdk/issues/1831
This is blocking https://github.com/famedly/matrix-dart-sdk/pull/2040
I've tested it MULTIPLE times trying out so many things. Please ping me if you want to review it together on a call!

fix: room prev_batch set incorrectly follow-up

---

.codecov.yaml
.github/workflows/app.yml

https://app.codecov.io/github/famedly/matrix-dart-sdk

feat: upload code coverage to codecov

---

lib/matrix.dart
lib/msc_extensions/extension_timeline_export/timeline_export.dart
test/msc_extensions/timeline_export_test.dart

Closes https://github.com/famedly/product-management/issues/2858

feat: export timeline events

---

pubspec.yaml
test/webrtc_stub.dart

Needed for https://github.com/famedly/app/pull/6403

chore: upgrade webrtc_interface to v1.2.2+hotfix.1

---

lib/src/client.dart
test/room_test.dart

close #https://github.com/famedly/app/issues/6398

Deleting last message is edited

---

lib/src/user.dart

Closes https://github.com/famedly/matrix-dart-sdk/issues/305

fix: add proper description for `User` class

---

lib/fake_matrix_api.dart
lib/src/client.dart
test/timeline_test.dart

fixes: https://github.com/famedly/app/issues/6465

fix: make sure prev_batch is updated after a limited timeline

---

lib/src/utils/markdown.dart
test/markdown_test.dart

Also fixes a bug where a room pill was not rendered as link.

feat: Switch to github flavor markdown to render checkboxes

---

lib/src/database/database_file_storage_io.dart
pubspec.yaml

fix: fix the issue that user avatar can not be loaded on windows

---

lib/src/room.dart

Forgot to remove them in the last PR.

chore: Remove unused callbacks
