famedly/matrix-dart-sdk

lib/src/database/database_api.dart, lib/src/database/hive_collections_database.dart, lib/src/database/hive_database.dart, lib/src/room.dart
At least in our CI this throws a null assertion error and since we explicitly expect this to sometimes be null in our code, we should store it as such.
=> fix: storing the end of history pagination

lib/matrix.dart, lib/src/utils/event_localizations.dart, lib/src/utils/matrix_default_localizations.dart, lib/src/utils/matrix_localizations.dart, lib/src/utils/room_member_change_type.dart, test/event_test.dart
For easier handling and
comparing of m.room.member
state events to better
know what these event
actually changes.
Part of https://github.com/famedly/product-management/issues/496
=> feat: Implement member change type

lib/src/event.dart, lib/src/utils/markdown.dart, pubspec.yaml, test/markdown_test.dart, test/room_test.dart
fixes https://github.com/famedly/product-management/issues/289
Removes two test cases in the markdown test which do not work anymore.
Reason for this is that just parsing a word inside of $$ word $$
katex is not valid anyway because katex is only made for mathematical
things. So the output is undefined behavior anyway.
=> refactor: Update markdown

lib/src/timeline.dart
Hi there
Found a bug in _requestEvents. `historyCount` is supposed to be applied to `limit`, however it is using Room.DefaultHistoryCount.
Also, is it possible to filter event types? Otherwise, when retrieving historical chat, there might be events not supposed to be shown.
=> fix: fixed hardcoded historyCount

lib/encryption/key_manager.dart, test/encryption/online_key_backup_test.dart, test/fake_matrix_api.dart
This makes it possible to load
and sync all room keys
right after the bootstrap if the
app wants to do this.
=> feat: Add methods to load all room keys from online key backup

lib/src/client.dart, lib/src/room.dart
- store left rooms in archive during sync (as well as they are removed on join already)
- refactor room archive code
- fix typo
Internal reference: SMC-385
=> chore: incrementally add left rooms to archive

lib/src/client.dart, lib/src/room.dart, lib/src/voip/voip_room_extension.dart
We were accumulating stale call checkers with every room. Also when we removed a room, the stale call checker kept running in some instances. We can just run the checker after the sync without a timer though, which means we don't need to clean up the timers in the end and we don't need to call sync in every call checker.
=> stale call checker leak

analysis_options.yaml, lib/encryption/encryption.dart, lib/encryption/key_manager.dart, lib/encryption/olm_manager.dart, lib/encryption/ssss.dart, lib/encryption/utils/base64_unpadded.dart, lib/encryption/utils/key_verification.dart, lib/src/client.dart, lib/src/database/hive_collections_database.dart, lib/src/event.dart, lib/src/room.dart, lib/src/timeline.dart, lib/src/utils/device_keys_list.dart, lib/src/utils/native_implementations.dart, lib/src/utils/run_in_root.dart, lib/src/utils/uia_request.dart, lib/src/utils/web_worker/native_implementations_web_worker.dart, lib/src/voip/call.dart, lib/src/voip/conn_tester.dart, lib/src/voip/group_call.dart, lib/src/voip/utils.dart, lib/src/voip/voip.dart, test/client_test.dart, test/database_api_test.dart, test/device_keys_list_test.dart, test/encryption/key_manager_test.dart, test/fake_matrix_api.dart, test/room_archived_test.dart, test/timeline_context_test.dart, test/timeline_test.dart
I guess the only controversial change is the runInRoot stuff, but I don't see, why we would ever want to await those. The few cases, where we do, seem to fit better when we just await them directly?
=> stricter lints

test/fake_database.dart
Since we can't pass the fake filesystem to hive, instead we just store the database in a temporary directory.
=> fix: in memory database is not actually in memory

lib/src/timeline.dart
https://github.com/famedly/matrix-dart-sdk/issues/255
=> fix: Delayed encrypted event in timeline not added to aggregated events

.github/workflows/app.yml, .gitlab-ci.yml, lib/matrix.dart, lib/src/database/indexeddb_box.dart, lib/src/database/matrix_sdk_database.dart, lib/src/database/sqflite_box.dart, pubspec.yaml, test/box_test.dart, test/database_api_test.dart, test/fake_database.dart
Another approach to add former fluffybox directly to
the sdk. So we avoid any
requirement for a new name.
Just name it "MatrixSdkDatabase".
- FluffyChat latest main in profile mode
- Flutter 3.16.0
- Fairphone 5 with Android 13
- Account on [famedly.de](http://famedly.de/) Synapse with 169 rooms
- Branch: main
- Initial sync: Benchmark: Process sync -> 10181 ms (3955 items, 2.574209860935525 ms/item)
- App-start after initial sync: 
- Benchmark: Build database -> 114 ms
- Benchmark: Get all user device keys from store -> 1431 ms
- Benchmark: Get room list from store -> 691 ms
- Branch: krille/add-matrix-sdk-database
- Initial sync: Benchmark: Process sync -> 5248 ms (3961 items, 1.3249179500126231 ms/item)
- App-start after initial sync:
- Benchmark: Build database -> 320 ms
- Benchmark: …
=> feat: Add native sqflite indexeddb database

lib/src/database/hive_collections_database.dart, lib/src/database/matrix_sdk_database.dart, lib/src/utils/copy_map.dart
Unfortunately we need to copy
all maps. I took the opportunity
and abstracted the copy map
method to utils. I kept the
copyMap method as a
reference in HiveCollections
database to not require a
huge refactoring there as we
are going to ditch it anyway.
=> fix: Copy all maps got from database

lib/src/client.dart, lib/src/database/database_api.dart, lib/src/database/hive_collections_database.dart, lib/src/database/hive_database.dart, lib/src/database/indexeddb_box.dart, lib/src/database/matrix_sdk_database.dart, lib/src/database/sqflite_box.dart, test/box_test.dart, test/database_api_test.dart, test/fake_database.dart
This adds a delete database
method used for migration to
correctly delete the whole
legacy database instead just
empty it.
=> refactor: Add delete database method

lib/src/room.dart, test/room_test.dart
This makes it possible to
load users lazy
for rooms to calculate the
name and the avatar. The
changes explain the new
behavior in detail in the
dart docs. The old
avatar getter now only
returns the avatar from the
room state m.room.avatar.
=> refactor: Make getDisplayname and calcAvatar of room async

lib/src/client.dart
This caches the `getConfig` request which is rate-limited.
=> feat: cache getConfig request

lib/src/room.dart
This refactors three methods
regarding powerlevels. It
makes them a little bit more
readable and removes
unnecessary checks. it
also changes the canSendDefaultMessage
method in a way that it also
checks the events map in the
powerlevels so that it returns
true if message events are
overwritten there. It also
improves the dart docs and
explains in more detail what it
does.
=> fix: canSendDefaultMessage ignores overwritten events

lib/src/voip/call.dart, lib/src/voip/voip.dart, test/calls_test.dart, test/client_test.dart, test/fake_matrix_api.dart, test/room_archived_test.dart, test/webrtc_stub.dart
=> feat: add tests for calls

lib/src/room.dart
This creates the timeline object
earlier in the Room.getTimeline() method.
This results to that the
Timeline object already starts
to listen on the event stream
while the getTimeline() method
requests users from the database
and tries to decrypt room
events. I assume that this
causes the problem that
on timeline creation new
events get lost because they
come in, while getTimeline() is
not yet completed but the
onEvent stream is not yet
connected at the same time.
=> refactor: Connect timeline to event updates earlier

scripts/test.sh
note: this probably does not help us a lot atm given that the base github runner is a 2 core vm
=> chore: throw more threads at dart test

lib/encryption/ssss.dart, lib/encryption/utils/bootstrap.dart, test/encryption/ssss_test.dart
Fixes: https://github.com/famedly/product-management/issues/1401
fixes race where sometimes you miss the secrets in sync
edit from product: this also closes https://github.com/famedly/matrix-dart-sdk/pull/1584
=> fix: validate account_data values instead of checking them in syncUpdates

test/database_api_test.dart
This does not yet test on
Android but at least makes sure
that this problem does not
occur when using future
databases.
=> ci: Test that database can write and read at least 5mb of data

lib/src/database/matrix_sdk_database.dart
I don't know why but using concatonating produces type errors in one of 1000 times because one of these lists becomes a List<dynamic> while this should actually not be possible after casting them. Maybe that's a bug in Dart itself? However I have verified in dartpad that  it works this way.
=> fix: Type error when combining dynamic lists

lib/src/client.dart, lib/src/utils/client_init_exception.dart, test/client_test.dart
This changes the behavior
when client init fails. It
no longer calls logout and does
only clear local data while
returning all available
information in a new
exception type so that the
SDK consumer can decide
to logout or try again to init
with these information. This
should make it much more rare
that users loose their sessions.
=> refactor: Throw client init exception on client init fail

lib/src/room.dart
This creates a set before
requesting users from the
database. This prevents
doing the same check for
the same user multiple
times and also prevents
concurrent modifications
of the event list.
Fixes https://github.com/krille-chan/fluffychat/issues/810
=> refactor: Improve getTimeline senders

lib/src/database/indexeddb_box.dart
This is similar to the bug
in the sqflite but now for
the indexeddb.
=> fix: Correctly null cache in transactions for indexeddb

lib/src/database/hive_database.dart, lib/src/database/indexeddb_box.dart, lib/src/database/sqflite_box.dart, lib/src/database/zone_transaction_mixin.dart
This refactors the transaction
workaround with
"zone transactions" and
abstracts them in a mixin. Then
it just uses this mixin in the
HiveDatabase and the
sqflite_box and also applies
them on indexedDB to
fix transactions on web.
=> fix: Transactions on web by doing them in the same way as on io

lib/matrix.dart, lib/src/database/sqflite_encryption_helper.dart, lib/src/database/sqflite_encryption_helper/io.dart, lib/src/database/sqflite_encryption_helper/stub.dart, pubspec.yaml
This patch introduces a helper class for SQfLite encryption related operations.
Most matrix clients will encrypt their sqlite database at rest. Since this is a quite fragmented task using the Flutter sqlite ecosystem, this helper aims to simplify some more complex operations.
It in particular helps with the following tasks :
- loading the correct shared objects / dynamic libraries for sqlcipher
- check whether a database is encrypted
- migrate an unencrypted SQLite database to SQLCipher
- apply the cipher to a database while opening it and ensure it loads
This code is not exactly matrix related, though presumably any matrix client will use parts of it.
Possible regressions :
- `package:sqlite3` became a direct dependency. As of now it already was a transitive dependency of the SDK itself.
=> feat: add SQfLite encryption helper

lib/src/database/indexeddb_box.dart
Currently, the boxNames object is a Set, which causes this error when calling it: "Unable to clear database - NotFoundError: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found."
=> fix: convert boxNames to List in clear function when creating transaction

lib/src/room.dart
Previously archived rooms where called Empty chat (was <Your own username>).
Now the other username is selected in case of direct chats that are archived, via the room-member-states and client-userID
=> fix: Use name of other participant on archived rooms

lib/src/client.dart
This makes use of dart
records to return three
different values for one
method. This makes the
special class no longer
necessary just for
returning data.
=> refactor: Use dart records for checkHomeserver method

lib/src/database/indexeddb_box.dart, lib/src/database/matrix_sdk_database.dart, lib/src/database/sqflite_box.dart, test/box_test.dart
Usually we want to delete a corrupted database. To do this
we need to init the BoxCollection first
which is not possible with a
corrupted database.
To fix this, this PR makes the
delete method a static function so that we can delete a
database at any time. This
makes it no longer necessary
to store the database factory
in the boxcollection so I
have removed it.
=> fix: Make database deleteable without the need to init the boxcollection

lib/src/room.dart
When user A invites user B to
a group chat, the avatar getter
should not return the
avatar of the inviting user A.
This is not intuitive. A client might
decide to do so but IMO it makes
no sense to do this by default.
If the
room is a DM invite, user A's
avatar is already used in the
code block before.
=> fix: Do not use invitor avatar_url for room

pubspec.yaml
Right now, only dart sdk versions >= 3.3.0 are supported. This PR downgrades `sqflite_common_ffi` to `2.3.2+1` in order to support dart sdk v3.2.x.
=> chore: downgrade sqflite_common_ffi to support dart sdk v3.2.0

lib/src/room.dart
This fixes the bug that the
actual dart Map in the state
has been manipulated because
we have not worked with a
copy of the map. Also this
crashes if the powerlevelmap
would had a wrong type in
users.
=> fix: Make room.setPower more type safe and avoid change powerlevel in RAM before sending request to server

lib/matrix_api_lite/model/presence_content.dart
Observed by using FluffyChat and conduit/conduwuit as the server
Example:
```
@nomad:daedric.net: {type: m.presence, content: {currently_active: false, last_active_ago: 1712913753736, presence: , status_msg...}
```
=> Don't fail sync if a presence event contains an empty presence field

lib/src/room.dart
This makes sure that the
users for an invitation are
correctly loaded so that we
can display the avatar, the
room displayname and
wether the room is a direct
chat or not.
After app restart invitation looked like this:
After app restart with this fix:
=> fix: Fetch invite state after restart app

lib/src/event.dart
This brings more problems than it
helps. It leads to bugs like flickering
of sending images and also
confuses the user. This should
either be handled by the app
or the user.
Closes https://github.com/famedly/product-management/issues/1977
=> refactor: Removes the behavior of deleting an event if the file is no longer cached

lib/src/client.dart, lib/src/event.dart, lib/src/event_status.dart, lib/src/timeline.dart, test/event_test.dart, test/timeline_context_test.dart, test/timeline_test.dart
Fixes https://github.com/famedly/product-management/issues/1984
This fixes several problems. First
sending a fake event through the
onEventUpdate stream was not a
good design and lead to problems
if you expect a timeline event but
then are unable to build the
event from json. This now uses
a new stream in the Client which
is listened to in the timeline to
delete an event which should be
much more reliable.
It also now throws an exception
if deleting the event fails
instead of returning true or false.
A deprecation note is added.
It also removes the behavior of
silently delete a file event where
the file is not stored. This is
confusing for the user and the
event should stay in the timeline
until the user activly decides to
try to send it again or delete the
message.
=> refactor: delete not sent events without eventupdate stream workaround

lib/src/room.dart, lib/src/voip/call_session.dart
This lead to the huge problem that there is no
user feedback between sending a message and
seeing it in the timeline as it is encrypted
before the first user feedback is shown. But
the encryption step is async and also includes
fetching devices if necessary so that can take
seconds or even forever on bad internet
connection.
=> revert: Check size before fake sync

lib/matrix_api_lite/generated/model.dart, lib/matrix_api_lite/generated/model.g.dart
This adds the support for JWT authentication. It's now as easy as using the following code.
```dart
LoginResponse result = await _client.login(LoginType.mLoginJWT, token: accessToken);
```
In Synpase config file, add the following to allow JWT auth:
```yaml
jwt_config:
enabled: true
secret: "YOUR_SECRET"
algorithm: "HS256"
```
For more details, please refer to [JWT Login Type](https://matrix-org.github.io/synapse/latest/jwt.html#jwt-login-type)
=> feat: support for JWT authentication

lib/src/client.dart
The ensureNotSoftLoggedOut()
method must be called before
we do any network request.
With having the sync filter
check before, we send a
failing POST request with the
possible wrong access token
which then would let the app
logout itself.
=> fix: ensureNotSoftLoggedOut must be called before network reqeust in syncFilter check

lib/encryption/utils/stored_inbound_group_session.dart, lib/src/database/matrix_sdk_database.dart
This should highly increase the
performance as right now for every sync
ALL inbound group sessions are loaded
from the database and checked if
they need an upload. So if a user
has 10k stored sessions locally, this
would probably let the whole application
lag a lot. This stores the sessions which
need upload in a different table now,
similar how we do this with the to
device queue.
Closes https://github.com/famedly/matrix-dart-sdk/issues/1587
=> refactor: Store not uploaded group sessions in its own database queue

lib/matrix_api_lite/generated/api.dart, lib/matrix_api_lite/matrix_api.dart, lib/src/room.dart
Needed for https://github.com/famedly/product-management/issues/2019
Also refer https://github.com/famedly/dart_openapi_codegen/pull/47 which has the actual change for code generation.
=> perf: check event size in bytes without encoding twice

lib/src/voip/backend/livekit_backend.dart, lib/src/voip/group_call_session.dart
For: https://github.com/famedly/product-management/issues/2051
Relevant app PR: https://github.com/famedly/app/pull/5879
with this you can now send the key before joining the call to the participants, make sure to call onMemberStateChanged first to ensure groupCall.participants is populated
=> feat: make voip key generator public

lib/src/voip/backend/call_backend_model.dart, lib/src/voip/backend/livekit_backend.dart, lib/src/voip/backend/mesh_backend.dart, lib/src/voip/group_call_session.dart, lib/src/voip/voip.dart
fix: only fire backend.onNewParticipant and backend.onLeftParticipant when it is not the local participant, this fixes the issue where onNewParticipant would get triggered when it detects a new call even though you were not in the call, as of now there is no code in those functions which needs to be triggered before you have joined the call so this should be fine
chore: also improve participants join leave tracking logic
=> preShareKey improvements

lib/src/voip/utils/famedly_call_extension.dart, lib/src/voip/voip.dart
=> fix: make sure room is postLoaded before starting calls

lib/src/client.dart, lib/src/room.dart, test/client_test.dart
This deprecates all streams which can
be created by using client.onSync
anyway for a more predictable state
handling in consuming apps.
=> refactor: Deprecate Streams in favor of client.onSync

lib/src/room.dart
This has been set to false
to prevent storing global
user profiles as member states
in the database. However
looks like this is already
solved below. We can
safely store the profile
in the local cache, otherwise
we cannot calc the body
for an event synchroniously.
closes https://github.com/famedly/product-management/issues/2039
=> fix: Requst profiles for left users

lib/src/voip/call_session.dart
Related: https://github.com/famedly/product-management/issues/2070
=> fix: do not fire missedCall on answeredElseWhere

lib/src/database/hive_collections_database.dart, lib/src/database/hive_database.dart, lib/src/database/matrix_sdk_database.dart, test/database_api_test.dart
This could sometimes lead to the room name or the names of members in the room being incorrect.
=> fix: state updates being also applied when fetching history

lib/src/voip/utils/voip_constants.dart
element call uses 3 and 5 seconds respectively, this should be fine.
Now you do not make a new key until there's been 4 seconds where no one left the call before the previous leave. And an additional 6 seconds for the key to be used to actually encrypt the streams to make sure everyone has them.
=> chore: bump make and use key delays to have more buffer

lib/fake_matrix_api.dart, lib/src/room.dart, test/room_test.dart
This completely redoes the requestUser function.
It now doesn't stop requesting a user forever just because of a network error. But redundant calls are still deduplicated, however their parameters are taken into account now.
It also now only calls onUpdate and onRoomState when there is actually new state. This way apps can just listen to updates to rerender instead of having to implement the deduplication themselves.
It also now doesn't treat member events without membership as "join" anymore. And lookup errors don't cause an empty user to get inserted into the room state.
In general this should still request the profile from the server, if the displayname is unset in a leave event, but it should also allow the app to actually settle in the tests.
=> fix: Request user causing state update loops for apps

lib/src/voip/backend/livekit_backend.dart, lib/src/voip/utils/voip_constants.dart
well that wasn't really helpful because you could not end up in a state where you have to wait for an additional 6 seconds before the key you got was just used.
we always send the latest key (to avoid breaking secrecy) but 6 seconds might have been too long for UX
also now exposes those timeouts
=> chore: allow clients to set their own voip key delays

lib/src/room.dart, lib/src/utils/matrix_default_localizations.dart, lib/src/utils/matrix_localizations.dart
Group chats with no user
avatar should return null for
the room.avatar getter and not
a random hero avatar. This could
otherwise lead to confusion as
it looks like this is a DM which
is not the case.
For the name we should also
not just display the name of
the invitor like in a DM even for
group chats, but some more
additional information. I found
a String for
invites quite useful here as
this would name rooms without
a m.room.name like this:
"Invited by $senderName"
which should be short enough.
The alternative
"You have been invited by $senderName" could be too
long IMO.
=> refactor: Better avatar and names for invites

lib/src/database/matrix_sdk_database.dart
clears database to handle any old state seen in history getting applied bug bc336709af6e0a0a7ec132db991a9418c0f0b149
=> fix: bump database version to v9

lib/src/client.dart
If we fail to handle the
soft logout, we should call
the logout endpoint to
delete the device from
the server instead of just
clear the client.
Closes https://github.com/famedly/product-management/issues/2292
=> fix: Call logout on soft logout fail

.github/workflows/app.yml, lib/src/client.dart, test/client_test.dart
Synapse includes the room in both sections if you have both an invite->leave and a leave->invite transition in one sync response. Transitions in the other order are only included once (in the leave section) it seems, so this should work correctly in all cases.
Fixes https://github.com/famedly/product-management/issues/2283
=> fix: leave->invite in the same sync would hide the invite

lib/src/room.dart
closes https://github.com/famedly/product-management/issues/2137
Got confirmation from @phillshort that this fixes the bug!
=> fix: App freezes because of recursive loop with getLocalizedDisplayname() call

lib/fake_matrix_api.dart, lib/src/client.dart, lib/src/event.dart, lib/src/utils/uri_extension.dart, lib/src/utils/versions_comparator.dart, test/event_test.dart, test/mxc_uri_extension_test.dart
The ideal way to fix this would be autogen with the v1.11 spec. But because it changed from openapi v2 to v3 that looks like a bit more work than expected. Separating out auth media stuff from that because of urgency.
To test these changes please make sure your server properly registers the new media endpoints. Famedly servers do not atm because of worker misconfiguration. Tracking issue: https://github.com/famedly/infra-meta/issues/1688
=> feat: support for authenticated media

.github/workflows/app.yml, lib/src/database/sqflite_encryption_helper/io.dart
I guess no one ever noticed, but obviously the path of the SQLCipher build on macOS is relative to the build app on macOS. I double checked in both release and debug mode, this is the correct path for the SQLCipher dylib on macOS. The `Current` in the path defines it automatically chooses the matching one whether on aarch64 or amd64.
=> fix: SQLCipher dylib location on macOS builds

lib/src/client.dart, lib/src/database/database_api.dart, lib/src/database/hive_collections_database.dart, lib/src/database/hive_database.dart, lib/src/database/matrix_sdk_database.dart, test/client_test.dart
- BREAKING: remove `DiscoveryInformation` from the `checkHomeserver` response tuple
- BREAKING: create `DatabaseApi.storeWellKnown` method
- BREAKING: create `DatabaseApi.getWellKnown` method
- add new getter `Client.wellKnown` containing cached `DiscoveryInformation`
- override `Client.homeserver` to invalidate `Client.wellKnown` in case the domain changed
- override `Client.getWellknown` to cache the resolved `DiscoveryInformation`
- add tests for well-known cache
Fixes: https://github.com/famedly/matrix-dart-sdk/issues/1865
=> feat: cache .well-known data

lib/src/room.dart
Fixes: https://github.com/famedly/product-management/issues/2319
tldr  notification > requestUser > requestState fails  > requestProfile > updates RoomMember stateKey with bad data (data with no longer is_direct or the membership)
=> fix: race condition between getState and requestUser updates

lib/encryption/key_manager.dart, lib/matrix_api_lite/model/sync_update.dart, lib/src/database/indexeddb_box.dart, lib/src/database/sqflite_box.dart, test/room_archived_test.dart
When decrypting the last event for archived rooms when a room key is received, we used to send a synthetic SyncUpdate. This however put the archived room into the join section, which converted the room to a joined room. We need to respect what section the room was in when sending synthetic SyncUpdates.
fixes https://github.com/famedly/matrix-dart-sdk/issues/1916
=> fix archive rooms becoming joined

.github/workflows/app.yml, .github/workflows/versions.env, lib/encryption/olm_manager.dart, lib/fake_matrix_api.dart, test/calls_test.dart, test/client_test.dart, test/device_keys_list_test.dart, test/encryption/cross_signing_test.dart, test/encryption/key_request_test.dart, test/encryption/key_verification_test.dart, test/fake_client.dart, test/room_test.dart, test/timeline_test.dart, test/user_test.dart
This does various fixes throughout our tests to speed them up as well as prevents us from doing redundant work on sync.
1. Removes a 5 second sleep from the initial sync. There is no need for that and if we want to test something with such a delay, we should do that explicitly instead of in every test.
2. Deduplicates OTK uploads. This means we don't redundantly create OTKs when our upload key request is slower than the next sync. This might cause delays in OTK uploads until the next sync after an upload succeeds, but might also fix a few edge cases, where we may have overwritten our own OTKs multiple times and caused UTDs.
3. Removes a few key uploads in the common tests. We used to only ever return 20 stored OTKs (or null) in sync, which caused us to generate new keys and waste CPU …
=> Speedup tests

lib/src/room.dart, test/room_test.dart
The problem here is that we
have not created a deep copy
of the power level map. By using .copy() we create a
deep copy now.
Closes https://github.com/famedly/product-management/issues/2412
=> fix: Change power level without changing memory

lib/src/event.dart, test/event_test.dart
See the additional test cases. There are still some weird edge cases, but those are documented in the tests now.
=> Fix various edge cases in the unlocalized body calculation

.github/workflows/versions.env, lib/matrix_api_lite/generated/model.dart, lib/src/voip/backend/livekit_backend.dart, lib/src/voip/backend/mesh_backend.dart, lib/src/voip/models/call_participant.dart, lib/src/voip/models/voip_id.dart, pubspec.yaml
autogen script change: https://github.com/famedly/dart_openapi_codegen/pull/50
=> feat: BREAKING CHANGE add equality, hashcode and toString helper overrides to autogenerated code

lib/encryption.dart, lib/matrix.dart, lib/matrix_api_lite.dart, lib/msc_extensions/extension_recent_emoji/recent_emoji.dart, lib/msc_extensions/msc_1236_widgets/msc_1236_widgets.dart, lib/msc_extensions/msc_2835_uia_login/msc_2835_uia_login.dart, lib/msc_extensions/msc_3814_dehydrated_devices/msc_3814_dehydrated_devices.dart, lib/src/utils/crypto/subtle.dart, pubspec.yaml
The library annotations are a new lint and we have no need to specify a custom library name anywhere. The JS annoation on the library also did nothing, since it doesn't default to the library name in dart and only modifies the prefix of functions if you pass in a custom name.
The sqflite_common_ffi I removed the upper constraint, which allows us to use a newer version if our dart version is new enough, but I left it at the original version because there is no need to require a higher minimum currently.
=> chore: Upgrade dependencies

lib/src/client.dart, lib/src/voip/utils/async_cache_try_fetch.dart
This fixes for example that if a
fetch from an asynccache once
failed it never gets retried. So we
only want to cache results, not
exceptions/errors
=> fix: AsyncCache is not invalidating on error

lib/src/voip/call_session.dart
Closes https://github.com/famedly/matrix-dart-sdk/issues/1967
=> fix: rejecting a call doesn't send m.call.reject event

lib/src/room.dart
Part of https://github.com/famedly/product-management/issues/2656. This will throw the error if we failed to send the reaction.
=> Throw error on failed reaction send

lib/src/client.dart
Without this null check the cache for the well-known data gets deleted everytime the Client gets initialized, making it useless across app restarts.
=> don't reset wellknown cache on Client initialization

lib/src/voip/README.md, lib/src/voip/backend/mesh_backend.dart, lib/src/voip/models/webrtc_delegate.dart, lib/src/voip/voip.dart, test/webrtc_stub.dart
I noticed that the SDK misses sending initial stream updates (in `onStreamAdd` and `onStreamRemove`) for both P2P and mesh calls in some cases. The easiest to reproduce would be an incoming P2P call where the `onStreamAdd` and `onStreamRemove` listeners are registered in `handleNewCall` VoIP method.
1. Start the flutter app in VS Code
2. Set a breakpoint within an if condition that check for the stream to not be local, inside the `onStreamAdd` callback
3. Start an outgoing call
4. Once the call is connected and the other person's media is shared, the debugger would stop at the breakpoint. This means that the `onStreamAdd` callback is working as expected.
5. Now, start the call from another device so that this device has an incoming call
6. Answer the call
7. Even after the call is …
=> fix: BREAKING! missed initial updates for stream listener callbacks in P2P & mesh calls

lib/encryption/encryption.dart, lib/src/client.dart, lib/src/utils/event_update.dart
This should removes an
unnecessary step of
json serialization and deserialization and should
therefore improve performance.
Gets rid of some unnecessary
code as well.
Related to https://github.com/famedly/product-management/issues/1875
=> refactor: Use Event instead of EventUpdate for pending decryption event queue and for decrypt events in general

lib/encryption/encryption.dart, lib/src/client.dart, lib/src/database/hive_collections_database.dart, lib/src/database/hive_database.dart, lib/src/database/matrix_sdk_database.dart, lib/src/utils/event_update.dart, test/client_test.dart
This handles room ephemerals
directly and not as room
event updates, which saves
one unnecessary step to json serialize and
deserialize. Handling those
as room event updates had
no benefit anyway so this
should speed up performance.
=> refactor: Do not handle ephemerals as EventUpdates

lib/src/client.dart, lib/src/database/database_api.dart, lib/src/database/hive_collections_database.dart, lib/src/database/hive_database.dart, lib/src/database/matrix_sdk_database.dart, test/database_api_test.dart
This changes the database
api a little bit so that it does
not unnecessarily serialize
and deserialize all
account data objects. Should
improve the performance of
the SDK.
Please note that in the hive
database(s) we create a
copy of the json map before
storing it. That is not necessary
for the matrix sdk database
as there the json map gets
serialized to a String anyway
inside.
=> refactor: Do not unnecessarily serialize and deserialize json for every account data object

lib/src/database/hive_collections_database.dart, lib/src/database/matrix_sdk_database.dart
Looks like room account data
was just forgotten in this
method which explains the
bug in FluffyChat when
I receive a DM and in the
push notification it is not
marked as DM sometimes.
=> fix: Also load room account data in getSingleRoom()

lib/src/client.dart, lib/src/database/database_api.dart, lib/src/database/hive_collections_database.dart, lib/src/database/matrix_sdk_database.dart, lib/src/utils/event_update.dart, test/client_test.dart, test/database_api_test.dart
This also makes sure that
room account data does not
get unnecessarily serialized
and deserialized before
storing it in the database.
For this it changes the
code flow at multiple
places.
=> refactor: Handle Room Account Data outside of Room Event Updates

lib/src/client.dart, lib/src/room.dart, test/room_test.dart
Something that has been bugging me for some time.
=> chore: BREAKING rename timeCreated to latestEventReceivedTime in Room

lib/encryption/encryption.dart, lib/encryption/key_verification_manager.dart, lib/src/client.dart, lib/src/database/database_api.dart, lib/src/database/hive_collections_database.dart, lib/src/database/matrix_sdk_database.dart, lib/src/event.dart, lib/src/room.dart, lib/src/timeline.dart, lib/src/utils/event_update.dart, test/client_test.dart, test/database_api_test.dart, test/encryption/key_verification_test.dart, test/matrix_database_test.dart, test/timeline_context_test.dart, test/timeline_test.dart
Fixes https://github.com/famedly/product-management/issues/1875
=> refactor: Use Event instead of EventUpdate for storing in db

lib/src/room.dart
I ran into a funny bug : 
- you get a new invite for a direct chat (in my case sent from Element)
- join the invite
- kill your client before ever loading the hero user
- your chat will for ever be called "Empty chat"
I figured out I ran into a state issue where the summary's `mHeros` was an empty list (not null !) but a direct chat user actually exists. The `Room.getLocalizedDisplayname` method now returns `Empty chat` as even an empty hero list is prioritized over a direct chat MXID. Right now, the direct chat MXID is only used if there is not even a hero list set.
I'd propose to simply override the hero list with the direct chat MXID in case the list is empty.
=> fix: priorize direct chat MXIDs over empty hero user list

lib/src/client.dart, lib/src/room.dart
Element actually does not do
this and use the linebreaks
inside of their <p> tags. It
works for our new html
rendering as well which is
already in FluffyChat.
=> refactor: Make converting linebreaks in markdowntohtml optional

lib/encryption/key_manager.dart
When using Set.from() then
it becomes a Set of
dynamics which disables the
Type checking.
By just changing this to
.toSet() it keeps the type.
=> refactor: Use .toSet() instead of Set.from()

lib/encryption/key_manager.dart
This bug seems to be in the
sdk for 5 years already without
anyone noticing. The method
loadInboundGroupSession
seems to return the wrong
variable when loading the
session from the key. While
the outboundgroupsession
loading method relies on
an inbound group session, it
silently marks the outbound
group session as invalid on
every restart and creates a
new one. This means we never
reuse megolm sessions after
restarting the client.
Fixing this will probably reduce
the amount of megolm sessions
used in a conversation by a lot
which could improve the
performance and make the
key backup more reliable.
Closes https://github.com/famedly/product-management/issues/2840
It looks like the bug was introduced 3 years ago while doing the null safe migration. Before the method looked like this:
```dart …
```
=> fix: Megolm sessions become invalid after restarting client

lib/src/client.dart, lib/src/room.dart, lib/src/utils/commands_extension.dart, test/commands_test.dart
While implementing some custom commands, I stumbled across some issues with the current command runner :
1. Currently, even Client-level commands such as `/join`, `/dm` etc. require to be entered with a `Room` present as parameter
2. Currently, commands have no way to provide output, such as a success message, some reference to e.g. a newly created room or any other information since the return parameter is currently usually an eventId used by the clients to confirm sending a message was successful.
3. Currently, \[matrix\] clients have no way to catch exceptions specific to the command execution, such as a missing or invalid parameter etc.
I have the following proposals to address these issues in the SDK's command execution :
- unify behavior of all message sending related command
- add …
=> feat: improve commands_extension

lib/src/client.dart, lib/src/utils/device_keys_list.dart, test/device_keys_list_test.dart
closes https://github.com/famedly/product-management/issues/2028
=> feat: (BREAKING) Make share keys with logic configurable

lib/src/client.dart, lib/src/event.dart, lib/src/user.dart, test/client_test.dart
closes https://github.com/famedly/matrix-dart-sdk/issues/1772
=> fix: Older state events overwrite newer ones on fetching history

lib/src/event.dart
"body: If filename is not set or the value of both properties are identical, this is the filename of the original upload. Otherwise, this is a caption for the file."
refer https://spec.matrix.org/latest/client-server-api/#mfile
=> fix: incorrect filename when caption is used in body of event

lib/fake_matrix_api.dart, lib/src/client.dart, test/client_test.dart
Should fix what https://github.com/famedly/matrix-dart-sdk/pull/2055 intended to do. Thanks @td-famedly for the test files.
=> fix: set prev_batch first time from sync response correctly

lib/src/event.dart, test/event_test.dart
Closes https://github.com/famedly/app/issues/6394
=> fix: Trim plaintext after removeMarkdown

lib/src/room.dart
This sometimes lead to the
problem that the timeline misses
the newest messages. Especially
when opening the app from a
notification this can happen.
=> fix: Do not load timeline while sync is processed

lib/src/event.dart, test/event_test.dart
Supports fallback for threads according to https://spec.matrix.org/v1.14/client-server-api/#fallback-for-unthreaded-clients
=> feat: Support fallback for threads in Event.getReplyEvent()

lib/src/client.dart
Recent changes in the SDK introduced to use the userID as primary source for the well-known URI. Sadly this only works if the user is already logged in. In order to make use of the `checkHomeserver` method, clients first pass a `homeserver` which is applied to the `Client` instance. The `checkHomeserver` method will then call `getWellKnown` before the MXID is actually known, the `Client.userID` is `null` thus.
Steps to reproduce :
- open https://fluffychat.im/web
- enter a homeserver URI (e.g. example.org) that does delegate the homeserver to a subdomain (e.g. matrix.example.org)
- see an error message
Potential regressions : well-known resolution won't work if the client provides the actual homeserver address (matrix.example.org) while the well-known is hosted on the base URI …
=> fix: null check on Client.userID in Client.checkHomeserver

lib/fake_matrix_api.dart, lib/src/client.dart, test/client_test.dart, test/encryption/key_manager_test.dart
closes https://github.com/famedly/product-management/issues/3190
This adds a check before the storeRoomUpdate() call
if the room is actually known. This has the effect
that the call of forgetRoom() is skipped.
The reason for this is an edge case in the database
implementation when calling getAllKeys(). This
somehow can corrupt the keys-cache and lead to
some problems. I wasn't able to fix this problem
yet so this refactoring is more a good-enough
workaround for now to not trigger it on an
initial sync. I plan to fix it with a different
approach which completely removes the keys-cache
in the future.
However this change leads to some problems in the
tests as they already rely on this edge case.
=> refactor: Ignore leave room update for unknown rooms

CHANGELOG.md, doc/end-to-end-encryption.md
Fixes https://github.com/famedly/matrix-dart-sdk/issues/2108
=> chore: Add hint to init vodozemac also in native implementations

lib/matrix_api_lite/matrix_api.dart
Makes the migration easier later :)
=> chore: Add deprecated type aliases for renamed models
